# This one is for music files and we only need to read from it!

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi