apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/users/haiqa/experiments/data